### ISSUE TITLE
How to get the results in the paper?

### ISSUE THREAD

**Issue by Outlande** [valeoai/PCAM#1]
I use the eval method from the README, but the results is worse:

SOFT result:
RTE all: 2.6929195
RRE all 1.755938845188313
Recall: 0.8468468468468469
RTE:  0.30647033
RRE:  0.41620454047369715
Times: 0.27450611107738326

Sparse Result:
RTE all: 3.8984199
RRE all 2.97438877706469
Recall: 0.4900900900900901
RTE:  0.37603837
RRE:  0.4989037670898464
Times: 0.2832888589950377

Do I need to modify any code to get the results showed in paper?

**Comment by anhquancao** [comment]
Hi @Outlande, we tested the provided code when released and obtained the results shown in the paper with the provided checkpoints. Did you retrain from scratch or use our provided pretrained checkpoint?
Also, could you provide more information e.g. which cmd did you use, the environment, and the dataset?

**Comment by Outlande** [comment]
The datasets is KITTI.
 I follow your instruction in README except the minkconv, which is V0.5.4. Could this be the problem

**Comment by Outlande** [comment]
> Hi @Outlande, we tested the provided code when released and obtained the results shown in the paper with the provided checkpoints. Did you retrain from scratch or use our provided pretrained checkpoint? Also, could you provide more information e.g. which cmd did you use, the environment, and the dataset?

The datasets is KITTI.
I follow your instruction in README except the minkconv, which is V0.5.4. Could this be the problem

**Comment by Outlande** [comment]
I'm very sorry, I find that I modified some parameters, now it worked well.
